// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: pkg/service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NucleiApi_Scan_FullMethodName = "/service.NucleiApi/Scan"
)

// NucleiApiClient is the client API for NucleiApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NucleiApiClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResult], error)
}

type nucleiApiClient struct {
	cc grpc.ClientConnInterface
}

func NewNucleiApiClient(cc grpc.ClientConnInterface) NucleiApiClient {
	return &nucleiApiClient{cc}
}

func (c *nucleiApiClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NucleiApi_ServiceDesc.Streams[0], NucleiApi_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NucleiApi_ScanClient = grpc.ServerStreamingClient[ScanResult]

// NucleiApiServer is the server API for NucleiApi service.
// All implementations must embed UnimplementedNucleiApiServer
// for forward compatibility.
type NucleiApiServer interface {
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResult]) error
	mustEmbedUnimplementedNucleiApiServer()
}

// UnimplementedNucleiApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNucleiApiServer struct{}

func (UnimplementedNucleiApiServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResult]) error {
	return status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedNucleiApiServer) mustEmbedUnimplementedNucleiApiServer() {}
func (UnimplementedNucleiApiServer) testEmbeddedByValue()                   {}

// UnsafeNucleiApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NucleiApiServer will
// result in compilation errors.
type UnsafeNucleiApiServer interface {
	mustEmbedUnimplementedNucleiApiServer()
}

func RegisterNucleiApiServer(s grpc.ServiceRegistrar, srv NucleiApiServer) {
	// If the following call pancis, it indicates UnimplementedNucleiApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NucleiApi_ServiceDesc, srv)
}

func _NucleiApi_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NucleiApiServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NucleiApi_ScanServer = grpc.ServerStreamingServer[ScanResult]

// NucleiApi_ServiceDesc is the grpc.ServiceDesc for NucleiApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NucleiApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.NucleiApi",
	HandlerType: (*NucleiApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _NucleiApi_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/service/service.proto",
}
